# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2019-05-28 06:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190528_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='hometown',
            field=models.CharField(default='福建', max_length=30),
        ),
    ]
