# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2019-05-28 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_employee_hometown'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='comment',
            field=models.CharField(blank=True, default='傻逼', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
